# Generated by Django 3.2.2 on 2021-05-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
