# Generated by Django 3.2.2 on 2021-05-22 15:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_contactform_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
        migrations.AddField(
            model_name='postpage',
            name='introduction',
            field=models.TextField(default='Type your introduction here ...'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='para1',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='para2',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='para3',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='quote',
            field=models.CharField(default='Quote from your blog here ...', max_length=300),
        ),
        migrations.AddField(
            model_name='postpage',
            name='titlePara1',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='postpage',
            name='titlePara3',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
