# Generated by Django 3.2.2 on 2021-05-31 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210522_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postpage',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
