# Generated by Django 3.2.2 on 2021-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_num',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='postpage',
            name='id_num',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
