# Generated by Django 3.2.2 on 2021-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210606_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='tag name', max_length=100),
        ),
        migrations.AddField(
            model_name='postpage',
            name='tags',
            field=models.CharField(default='tag name', max_length=100),
        ),
    ]
