# Generated by Django 3.2.2 on 2021-06-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210606_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='postpage',
            old_name='tags',
            new_name='tag',
        ),
    ]
