# Generated by Django 3.2.2 on 2021-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=9999999999, max_length=10),
        ),
    ]
